### PR TITLE
Fixed end of attributes regexp

### PR DESCRIPTION
**Pull request by iRet**
This fix will turn
image

To this
image

### CODE REVIEW

**Comment by iRet** [comment]
Don't merge, second commit not works as expected and requrie polishing,
However first solves problem for tag attributes.

**Comment by cannikin** [comment]
Looking good now?

**Comment by iRet** [comment]
@cannikin unfotunately no
Attributes and ruby line was fixed in multiline, but tags higlight was broken in some cases where tags not spaces by empty line. Need a fresh look.

**Comment by Igor10k** [comment]
@iRet Just wanted to contribute the same thing. Seems like changing `end` for `meta.section.attributes.haml` to `\\}(?!\\s*,)` is enough. Why did you bother with `source.ruby.embedded.haml`?

**Comment by iRet** [comment]
@Igor10k Hi.
That's enough for attributes hash, but not for ruby code line.

**Comment by Igor10k** [comment]
@iRet I thought this issue is only about attributes hash. Let's merge the attributes fix and create another issue for the ruby code line with some screenshots and a description of the problem as I don't understand what's wrong with it?

**Comment by iRet** [comment]
@Igor10k a good idea, I will remove unrelated lines from PR.
As for rubycode problems, please check https://github.com/cannikin/language-haml/issues/20

**Comment by Igor10k** [comment]
@iRet You should squash those 5 commits into one.

**Comment by cannikin** [comment]
Howdy! What's going on here, should I merge this?

**Comment by Igor10k** [comment]
@cannikin currently it's 5 commits for one changed line. I'd wait till he squashes the commits first.

**Comment by iRet** [comment]
@Igor10k thanks, now I know how to do squash :)

**Comment by Igor10k** [comment]
@iRet great :smile: 

@cannikin looks like it's time to merge now

**Comment by cannikin** [comment]
LET'S DO IT

**Comment by cannikin** [comment]
Released v0.20.0

**Pull request merged**
